function F = findFile_returnFPath()
%FINDFILE_RETURNFPATH Summary of this function goes here
%   Detailed explanation goes here

%TODO: make filter/title changeable.

filter = {'*.jpg; *.JPG; *.jpeg; *.JPEG; *.png; *.PNG; *.img; *.IMG; *.tif; *.TIF; *.tiff, *.TIFF','Supported Files (*.jpg, *.png, *.img, *.tiff,)'; ...
    '*.jpg','jpg Files (*.jpg)';...
    '*.JPG','JPG Files (*.JPG)';...
    '*.jpeg','jpeg Files (*.jpeg)';...
    '*.JPEG','JPEG Files (*.JPEG)';...
    '*.png', 'png Files (*.png)';...
    '*.PNG', 'PNG Files (*.PNG)';...
    '*.img','img Files (*.img)';...
    '*.IMG','IMG Files (*.IMG)';...
    '*.tif','tif Files (*.tif)';...
    '*.TIF','TIF Files (*.TIF)';...
    '*.tiff','tiff Files (*.tiff)';...
    '*.TIFF','TIFF Files (*.TIFF)';...
    '*.*', 'All Files (*.*)'};
title = 'Select an image file';

[file, path] = uigetfile(filter, title);

if isequal(file, 0)
    warning('File selection UI was canceled or other issue occured. Please try again.')
    return;
end

F = PathTools.FPath(path, file);

if ~F.isFile
    warning('Path is not a file. Please try again')
    clear('F');
    return;
end

end